name: resilient-snowpack-estimation
channels:
  - conda-forge
  - defaults
dependencies:
  - cycler=0.11.0
  - dask=2022.12.1
  - dask-core=2022.12.1
  - decorator=5.1.1
  - esda=2.5.1
  - fiona=1.9.5
  - folium=0.14.0
  - fsspec=2022.11.0
  - gdal=3.7.2
  - geopandas=0.14.0
  - geopandas-base=0.14.0
  - geos=3.12.0
  - hdf5=1.14.2
  - ipykernel=6.19.4
  - ipython=8.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.3
  - json-c=0.17
  - jupyter_core=5.1.2
  - jupyter_events=0.5.0
  - jupyterlab=3.5.2
  - jupyterlab_pygments=0.2.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - netcdf4=1.6.5
  - numpy=1.24.1
  - pandas=1.5.2
  - pickleshare=0.7.5
  - pip=22.3.1
  - proj=9.3.0
  - python=3.11.0
  - python-dateutil=2.8.2
  - rasterio=1.3.9
  - rich=13.3.5
  - scikit-gstat=1.0.10
  - scikit-image==0.22.0
  - scikit-learn==1.1.3
  - scipy=1.10.0
  - shapely=2.0.2
  - statsmodels=0.14.0
  - tqdm=4.66.1
  - wrf-python=1.3.4.1
  - xarray=2023.10.1
  - yaml=0.2.5
  - pip:
      - cmcrameri==1.7
      - virtualenv==20.17.1

  